### ISSUE TITLE
Find the real character encoding for transcripts

### ISSUE THREAD

**Issue by Dobby233Liu** [Dobby233Liu/garfield.csv#1]
http://john.ccac.rwth-aachen.de:8000 says a lot. Let's see what headers it returns.

**Comment by Dobby233Liu** [comment]
I did many expermients all pushed on pages branch

**Comment by Dobby233Liu** [comment]
```yaml
Date: Sun, 02 May 2021 04:01:28 GMT
Server: Apache/2.4.38 (Debian)
Last-Modified: Sat, 10 Feb 2007 11:03:42 GMT
ETag: "831-4291d3aac3f80-gzip"
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 1133
Content-Type: text/html
```
generated html is utf8
